<%@ Page Title="" Language="C#" MasterPageFile="~/site.Master" AutoEventWireup="true" CodeBehind="list.aspx.cs" Inherits="hrManage.list" %>
<asp:Content ID="Content1" ContentPlaceHolderID="headPlaceHoldar" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyPlaceHolder" runat="server">

    <asp:GridView ID="GridView1" CssClass="  table table-hover table-bordered table-responsive alert-info "  runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource3"></asp:GridView>

  
     <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>

  
     <asp:SqlDataSource ID="SqlDataSource3"  runat="server" ConnectionString="<%$ ConnectionStrings:hrmg4ConnectionString %>" SelectCommand="SELECT * FROM [registration]" UpdateCommand="UPDATE [registration] Set [FName]=@FName,[LName]=@LName,[FaName]=@FaName,[MaName]=@MaName,[Email]=@Email,[Contact]=@Contact,[DateofB]=@DateofB,[Paddress]=@Paddress,[Peraddress]=@Peraddress,[JoinDate]=@JoinDate,[Department]=@Department,[Designation]=@Designation,[LastDegree]=@LastDegree,[BasicPay]=@BasicPay Where [emp_id]=@emp_id" DeleteCommand="DELETE from [registration] Where [id]=@emp_id"></asp:SqlDataSource>
  

</asp:Content>
