<%@ Page Title="" Language="C#" MasterPageFile="~/site.Master" AutoEventWireup="true" CodeBehind="viewdpt.aspx.cs" Inherits="hrManage.viewdpt" %>
<asp:Content ID="Content1" ContentPlaceHolderID="headPlaceHoldar" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyPlaceHolder" runat="server">

    <asp:GridView ID="GridView1" CssClass="table table-hover table-bordered table-responsive alert-info " runat="server" AllowSorting="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="dpt_id" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
            <asp:BoundField DataField="dpt_id" HeaderText="Department ID" InsertVisible="False" ReadOnly="True" SortExpression="dpt_id" />
            <asp:BoundField DataField="dpt_name" HeaderText="Department Name" SortExpression="dpt_name" />
            <asp:BoundField DataField="Parentdpt" HeaderText="Parent Department" SortExpression="Parentdpt" />
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="Gray" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:mycon %>" SelectCommand="SELECT * FROM [Department]" UpdateCommand="UPDATE  [Department] Set [dpt_name]=@dpt_name,[Parentdpt]=@parentdpt Where [dpt_id]=@dpt_id " DeleteCommand="Delete From [Department] Where [dpt_id]=@dpt_id"></asp:SqlDataSource>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="foterPlaceHolder1" runat="server">
</asp:Content>
